# Generated by Django 3.2 on 2021-10-04 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='credits',
            field=models.IntegerField(default=0),
        ),
    ]
