# Generated by Django 3.2 on 2021-10-22 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0002_auto_20211017_0107'),
        ('non_basic_elements', '0002_nonbasicelement_study'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonbasicelement',
            name='study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nonBasicElement_study', to='study.study'),
        ),
    ]
