# Generated by Django 3.2 on 2021-10-22 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('non_basic_elements', '0003_alter_nonbasicelement_study'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nonbasicelement',
            name='student',
        ),
        migrations.RemoveField(
            model_name='nonbasicelement',
            name='subject',
        ),
        migrations.AddField(
            model_name='nonbasicelement',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
