# Generated by Django 3.2 on 2021-10-03 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('professors', '0001_initial'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imparts',
            fields=[
                ('subject', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='subjects.subject')),
                ('professor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='professors.professor')),
            ],
            options={
                'unique_together': {('subject', 'professor')},
            },
        ),
    ]
