# Generated by Django 3.2 on 2021-10-03 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imparts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imparts',
            options={'managed': False},
        ),
    ]
