# Generated by Django 3.2 on 2021-11-20 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0001_initial'),
        ('imparts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imparts',
            name='professor',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='professors.professor'),
        ),
    ]
