# Generated by Django 3.2 on 2021-10-03 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('value', models.IntegerField()),
                ('date_time_creation', models.DateTimeField()),
            ],
        ),
    ]
