# Generated by Django 3.2 on 2021-10-17 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('elements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicElement',
            fields=[
                ('element_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='elements.element')),
                ('subject', models.IntegerField()),
                ('professor', models.IntegerField()),
                ('visible', models.BooleanField(default=False)),
            ],
            bases=('elements.element',),
        ),
    ]
