# Generated by Django 3.2 on 2021-10-03 03:20

import compositefk.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('imparts', '0002_alter_imparts_options'),
        ('elements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicElement',
            fields=[
                ('element_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='elements.element')),
                ('subject', models.IntegerField()),
                ('professor', models.IntegerField()),
                ('imparts', compositefk.fields.CompositeForeignKey(null_if_equal=[], on_delete=django.db.models.deletion.DO_NOTHING, related_name='basicElement_imparts', to='imparts.imparts', to_fields={'professor': compositefk.fields.LocalFieldValue('professor'), 'subject': compositefk.fields.LocalFieldValue('subject')})),
            ],
            bases=('elements.element',),
        ),
    ]
