# Generated by Django 3.2 on 2021-10-22 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imparts', '0002_initial'),
        ('basic_elements', '0002_basicelement_imparts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicelement',
            name='imparts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='basicElement_imparts', to='imparts.imparts'),
        ),
    ]
