# Generated by Django 3.2 on 2021-10-22 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_elements', '0003_alter_basicelement_imparts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basicelement',
            name='professor',
        ),
        migrations.RemoveField(
            model_name='basicelement',
            name='subject',
        ),
    ]
