# Generated by Django 3.2 on 2021-11-20 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imparts', '0002_initial'),
        ('basic_elements', '0004_auto_20211022_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicelement',
            name='imparts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basicElement_imparts', to='imparts.imparts'),
        ),
    ]
