# Generated by Django 3.2 on 2021-11-20 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imparts', '0002_initial'),
        ('basic_elements', '0006_alter_basicelement_imparts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicelement',
            name='imparts',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='basicElement_imparts', to='imparts.imparts'),
        ),
    ]
